-define(PROTOCOL_VERSION, 1).

-define(MESSAGE_TYPE_ACK, 0).
-define(MESSAGE_TYPE_PING, 1).
-define(MESSAGE_TYPE_CONNECTION_REQ, 2).

-define(SERVER_MESSAGE_TYPE_ACK, 0).
-define(SERVER_MESSAGE_TYPE_PONG, 1).
-define(SERVER_MESSAGE_TYPE_CONNECTION_REPLY, 2).
-define(SERVER_MESSAGE_TYPE_ERROR, 3).

-define(ERROR_TYPE_NOT_MATCHING_PROTOCOL, 0).

