-define(PROTOCOL_VERSION, 1).

-define(MESSAGE_TYPE_SPECIAL, 0).
-define(MESSAGE_TYPE_ISALIVE, 1).
-define(MESSAGE_TYPE_CONNECTION_REQ, 2).

-define(SERVER_MESSAGE_TYPE_SPECIAL, 0).
-define(SERVER_MESSAGE_TYPE_CONNECTION_REPLY, 1).
-define(SERVER_MESSAGE_TYPE_ERROR, 2).

-define(ERROR_TYPE_NOT_MATCHING_PROTOCOL, 0).

